%% CoM sensitivity - baffled lenticular disc

if ~exist('cfg', 'var')
    project_config
end

fprintf('\n========================================\n');
fprintf('CoM SENSITIVITY - BAFFLED DISC\n');
fprintf('========================================\n');

%% ================================================================
% Dissertation figure style
% ================================================================

set(groot, ...
    'defaultFigureColor','w', ...
    'defaultFigureInvertHardcopy','off', ...
    'defaultAxesColor','w', ...
    'defaultAxesXColor','k', ...
    'defaultAxesYColor','k', ...
    'defaultAxesZColor','k', ...
    'defaultAxesGridColor',[0.70 0.70 0.70], ...
    'defaultAxesMinorGridColor',[0.82 0.82 0.82], ...
    'defaultAxesGridAlpha',0.35, ...
    'defaultAxesMinorGridAlpha',0.20, ...
    'defaultAxesFontName','Times New Roman', ...
    'defaultAxesFontSize',11, ...
    'defaultAxesLineWidth',0.8, ...
    'defaultAxesBox','on', ...
    'defaultTextColor','k', ...
    'defaultTextFontName','Times New Roman', ...
    'defaultTextFontSize',11, ...
    'defaultLineLineWidth',1.4, ...
    'defaultLineMarkerSize',6, ...
    'defaultLegendColor','w', ...
    'defaultLegendTextColor','k', ...
    'defaultLegendFontName','Times New Roman', ...
    'defaultLegendFontSize',10, ...
    'defaultLegendBox','off');


%% Model check

cfg.model.name = 'disc_lenticular_v04_balance';

if ~strcmp(cfg.model.name, model_name)
    error('Set cfg.model.name to disc_lenticular_v03 before running.');
end


%% Test conditions

altitude_km = 300;

aoa_values = [ ...
    -30, -20, -10, 0, 10, 20, 30];

aos_deg = 0;

% CoM displacement along Z [m]
com_z_values = [ ...
    -0.010, ...
    -0.006, ...
    -0.004, ...
    -0.002, ...
     0.000, ...
     0.002, ...
     0.004, ...
     0.006, ...
     0.010];


%% Atmospheric conditions

[param_eq, ~] = build_freestream( ...
    cfg, ...
    altitude_km);

q = 0.5 * ...
    param_eq.rho(6) * ...
    param_eq.vinf^2;


%% Load reference length

model_file = fullfile( ...
    cfg.paths.model_dir, ...
    [model_name '.mat']);

S = load(model_file);

Lref = S.meshdata.Lref;


%% Storage

nA = numel(aoa_values);
nC = numel(com_z_values);

AoA_deg      = zeros(nA*nC,1);
CoM_Z_m      = zeros(nA*nC,1);
CMy          = zeros(nA*nC,1);
PitchTorque  = zeros(nA*nC,1);
Drag_N       = zeros(nA*nC,1);
AreaProj_m2  = zeros(nA*nC,1);

row = 0;


%% Run sensitivity cases

for i = 1:nA

    for j = 1:nC

        row = row + 1;

        cfg_case = cfg;

        cfg_case.model.com_G_m = [ ...
            0;
            0;
            com_z_values(j)];

        case_out = run_adbsat_case( ...
            cfg_case, ...
            model_name, ...
            altitude_km, ...
            aoa_values(i), ...
            aos_deg, ...
            cfg.gsi.baseline_model);

        cd = -case_out.Cf_w(1);

        drag = ...
            q * ...
            case_out.AreaRef_m2 * ...
            cd;

        cmy = case_out.Cm_B(2);

        My = ...
            q * ...
            case_out.AreaRef_m2 * ...
            Lref * ...
            cmy;

        AoA_deg(row) = aoa_values(i);
        CoM_Z_m(row) = com_z_values(j);
        CMy(row) = cmy;
        PitchTorque(row) = My;
        Drag_N(row) = drag;
        AreaProj_m2(row) = case_out.AreaProj_m2;

    end
end


%% Results table

results = table( ...
    AoA_deg, ...
    CoM_Z_m, ...
    CMy, ...
    PitchTorque, ...
    Drag_N, ...
    AreaProj_m2);

disp(results)


%% Nominal AoA = 0 summary

nominal = results(results.AoA_deg == 0, :);

fprintf('\n========================================\n');
fprintf('AoA = 0 DEG CoM SUMMARY\n');
fprintf('========================================\n');

disp(nominal)


%% Find minimum absolute pitch moment at AoA = 0

[~, idx] = min(abs(nominal.CMy));

best = nominal(idx,:);

fprintf('\nLowest |CMy| at AoA = 0:\n');
fprintf('CoM Z:         %.3f mm\n', ...
    best.CoM_Z_m * 1000);

fprintf('CMy:           %.8e\n', ...
    best.CMy);

fprintf('Pitch torque:  %.8e N m\n', ...
    best.PitchTorque);


%% Save

out_file = fullfile( ...
    cfg.paths.project_results_dir, ...
    'com_sensitivity_baffle.mat');

save(out_file, ...
    'results', ...
    'nominal', ...
    'aoa_values', ...
    'com_z_values');

csv_file = fullfile( ...
    cfg.paths.project_results_dir, ...
    'com_sensitivity_baffle.csv');

writetable(results, csv_file);

fprintf('\nSaved:\n%s\n%s\n', ...
    out_file, ...
    csv_file);

fprintf('\nCoM sensitivity complete.\n');