%% environment_sensitivity.m
% Final environmental sensitivity analysis for disc_lenticular_v03.
%
% Evaluates controlled solar and geomagnetic activity scenarios across
% 200-400 km.
%
% IMPORTANT:
% These cases are sensitivity scenarios only. They are not forecasts of
% actual mission-date space weather.

if ~exist('cfg','var')
    project_config
end

cfg_run = cfg;
cfg_run.flags.verbose = 0;

%% ================================================================
% Dissertation figure style
% ================================================================

set(groot, ...
    'defaultFigureColor','w', ...
    'defaultFigureInvertHardcopy','off', ...
    'defaultAxesColor','w', ...
    'defaultAxesXColor','k', ...
    'defaultAxesYColor','k', ...
    'defaultAxesZColor','k', ...
    'defaultAxesGridColor',[0.70 0.70 0.70], ...
    'defaultAxesMinorGridColor',[0.82 0.82 0.82], ...
    'defaultAxesGridAlpha',0.35, ...
    'defaultAxesMinorGridAlpha',0.20, ...
    'defaultAxesFontName','Times New Roman', ...
    'defaultAxesFontSize',11, ...
    'defaultAxesLineWidth',0.8, ...
    'defaultAxesBox','on', ...
    'defaultTextColor','k', ...
    'defaultTextFontName','Times New Roman', ...
    'defaultTextFontSize',11, ...
    'defaultLineLineWidth',1.4, ...
    'defaultLineMarkerSize',6, ...
    'defaultLegendColor','w', ...
    'defaultLegendTextColor','k', ...
    'defaultLegendFontName','Times New Roman', ...
    'defaultLegendFontSize',10, ...
    'defaultLegendBox','off');

%% Settings

model_name = cfg.model.name;

altitudes_km = cfg.test.altitude_km;

aoa_deg = cfg.attitude.aoa_deg;
aos_deg = cfg.attitude.aos_deg;

gsi_model = cfg.gsi.baseline_model;

labels = cfg.env_sensitivity.labels;

f107_average_cases = ...
    cfg.env_sensitivity.f107_average;

f107_daily_cases = ...
    cfg.env_sensitivity.f107_daily;

ap_cases = ...
    cfg.env_sensitivity.ap_daily;

nCases = numel(labels);
nAltitudes = numel(altitudes_km);


%% Validate configuration

if numel(f107_average_cases) ~= nCases || ...
        numel(f107_daily_cases) ~= nCases || ...
        numel(ap_cases) ~= nCases

    error(['Environmental sensitivity arrays must contain ' ...
        'the same number of cases.']);

end


%% Load model reference length

model_file = fullfile( ...
    cfg.paths.model_dir, ...
    [model_name '.mat']);

if ~isfile(model_file)
    error('ADBSat model file not found: %s', model_file);
end

S = load(model_file);

Lref_m = S.meshdata.Lref;


%% Header

fprintf('\n');
fprintf('====================================================\n');
fprintf('FINAL v03 ENVIRONMENTAL SENSITIVITY\n');
fprintf('====================================================\n');

fprintf('Model:      %s\n', model_name);
fprintf('Altitude:   %.0f to %.0f km\n', ...
    min(altitudes_km), max(altitudes_km));

fprintf('AoA:        %.2f deg\n', aoa_deg);
fprintf('AoS:        %.2f deg\n', aos_deg);

fprintf('GSIM:       %s\n', gsi_model);
fprintf('Shadow:     %d\n', cfg.flags.shadow);
fprintf('Solar:      %d\n', cfg.flags.solar);

fprintf('CoM [m]:    [%+.6f  %+.6f  %+.6f]\n\n', ...
    cfg.model.com_G_m(1), ...
    cfg.model.com_G_m(2), ...
    cfg.model.com_G_m(3));

fprintf('Environmental sensitivity cases:\n');

for c = 1:nCases

    fprintf( ...
        '%-10s  F10.7 avg = %.1f, daily = %.1f, Ap = %.1f\n', ...
        labels{c}, ...
        f107_average_cases(c), ...
        f107_daily_cases(c), ...
        ap_cases(c));

end

fprintf(['\nNOTE: These are controlled sensitivity scenarios, ' ...
    'not mission forecasts.\n\n']);


%% Preallocate

nRows = nCases * nAltitudes;

Environment = strings(nRows,1);

Altitude_km = zeros(nRows,1);

F107_Average = zeros(nRows,1);
F107_Daily = zeros(nRows,1);
Ap_Daily = zeros(nRows,1);

Density_kgm3 = zeros(nRows,1);
Tinf_K = zeros(nRows,1);

Velocity_ms = zeros(nRows,1);
SpeedRatio = zeros(nRows,1);

DynamicPressure_Pa = zeros(nRows,1);

AreaProj_m2 = zeros(nRows,1);
AreaRef_m2 = zeros(nRows,1);

CD_ADBSat = zeros(nRows,1);
CD_projected = zeros(nRows,1);

Drag_N = zeros(nRows,1);

CMx_B = zeros(nRows,1);
CMy_B = zeros(nRows,1);
CMz_B = zeros(nRows,1);

My_Nm = zeros(nRows,1);

row = 0;


%% Run cases

for c = 1:nCases

    cfg_case = cfg_run;

    %% Apply environmental case

    cfg_case.env.f107_average = ...
        f107_average_cases(c);

    cfg_case.env.f107_daily = ...
        f107_daily_cases(c);

    % ADBSat/NRLMSISE configuration uses the full seven-element Ap vector.
    cfg_case.env.ap = ...
        repmat(ap_cases(c), 1, 7);


    fprintf('----------------------------------------------------\n');

    fprintf('%s environment\n', labels{c});

    fprintf('F10.7 average: %.1f\n', ...
        cfg_case.env.f107_average);

    fprintf('F10.7 daily:   %.1f\n', ...
        cfg_case.env.f107_daily);

    fprintf('Daily Ap:      %.1f\n\n', ...
        ap_cases(c));


    %% Altitude loop

    for a = 1:nAltitudes

        altitude = altitudes_km(a);

        row = row + 1;

        fprintf( ...
            'Case %2d of %2d: %-10s at %.0f km\n', ...
            row, ...
            nRows, ...
            labels{c}, ...
            altitude);


        %% Run ADBSat

        out = run_adbsat_case( ...
            cfg_case, ...
            model_name, ...
            altitude, ...
            aoa_deg, ...
            aos_deg, ...
            gsi_model);


        %% Environmental quantities

        Environment(row) = ...
            string(labels{c});

        Altitude_km(row) = ...
            altitude;

        F107_Average(row) = ...
            cfg_case.env.f107_average;

        F107_Daily(row) = ...
            cfg_case.env.f107_daily;

        Ap_Daily(row) = ...
            ap_cases(c);

        Density_kgm3(row) = ...
            out.rho_kgm3;

        Tinf_K(row) = ...
            out.Tinf_K;

        Velocity_ms(row) = ...
            out.vinf_ms;

        SpeedRatio(row) = ...
            out.speed_ratio;


        %% Dynamic pressure

        DynamicPressure_Pa(row) = ...
            0.5 * ...
            Density_kgm3(row) * ...
            Velocity_ms(row)^2;


        %% Aerodynamic quantities

        AreaProj_m2(row) = ...
            out.AreaProj_m2;

        AreaRef_m2(row) = ...
            out.AreaRef_m2;


        % Native ADBSat drag coefficient
        CD_ADBSat(row) = ...
            -out.Cf_w(1);


        % Projected-area-normalised drag coefficient
        CD_projected(row) = ...
            CD_ADBSat(row) * ...
            AreaRef_m2(row) / ...
            AreaProj_m2(row);


        % Dimensional drag
        Drag_N(row) = ...
            DynamicPressure_Pa(row) * ...
            AreaRef_m2(row) * ...
            CD_ADBSat(row);


        %% Moments about selected design CoM

        CMx_B(row) = ...
            out.Cm_B(1);

        CMy_B(row) = ...
            out.Cm_B(2);

        CMz_B(row) = ...
            out.Cm_B(3);


        % Dimensional pitch moment
        My_Nm(row) = ...
            DynamicPressure_Pa(row) * ...
            AreaRef_m2(row) * ...
            Lref_m * ...
            CMy_B(row);

    end

end


%% Build full results table

environment_results = table( ...
    Environment, ...
    Altitude_km, ...
    F107_Average, ...
    F107_Daily, ...
    Ap_Daily, ...
    Density_kgm3, ...
    Tinf_K, ...
    Velocity_ms, ...
    SpeedRatio, ...
    DynamicPressure_Pa, ...
    AreaProj_m2, ...
    AreaRef_m2, ...
    CD_ADBSat, ...
    CD_projected, ...
    Drag_N, ...
    CMx_B, ...
    CMy_B, ...
    My_Nm, ...
    CMz_B);


%% Display full results

fprintf('\n');
fprintf('====================================================\n');
fprintf('ENVIRONMENTAL SENSITIVITY RESULTS\n');
fprintf('====================================================\n\n');

disp(environment_results)


%% Baseline-altitude comparison

idx_baseline = ...
    Altitude_km == cfg.orbit.altitude_km;

baseline_environment_summary = ...
    environment_results(idx_baseline,:);


fprintf('\n');
fprintf('====================================================\n');
fprintf('BASELINE-ALTITUDE ENVIRONMENT COMPARISON\n');
fprintf('Altitude = %.0f km\n', cfg.orbit.altitude_km);
fprintf('====================================================\n\n');

disp(baseline_environment_summary)


%% Find quiet reference at baseline altitude

quiet_idx = find( ...
    idx_baseline & ...
    Environment == string(labels{1}), ...
    1);

if isempty(quiet_idx)

    error( ...
        'Quiet baseline environmental case was not found.');

end


%% Quiet reference values

rho_reference = ...
    Density_kgm3(quiet_idx);

CD_reference = ...
    CD_ADBSat(quiet_idx);

drag_reference = ...
    Drag_N(quiet_idx);

CMy_reference = ...
    CMy_B(quiet_idx);

My_reference = ...
    My_Nm(quiet_idx);


%% Relative changes at baseline altitude

DensityChangeFromQuiet_pct = ...
    100 * ...
    (baseline_environment_summary.Density_kgm3 ...
    - rho_reference) / ...
    rho_reference;


CDChangeFromQuiet_pct = ...
    100 * ...
    (baseline_environment_summary.CD_ADBSat ...
    - CD_reference) / ...
    CD_reference;


DragChangeFromQuiet_pct = ...
    100 * ...
    (baseline_environment_summary.Drag_N ...
    - drag_reference) / ...
    drag_reference;


CMyChangeFromQuiet_pct = ...
    100 * ...
    (baseline_environment_summary.CMy_B ...
    - CMy_reference) / ...
    CMy_reference;


MyChangeFromQuiet_pct = ...
    100 * ...
    (baseline_environment_summary.My_Nm ...
    - My_reference) / ...
    My_reference;


%% Add relative changes to baseline table

baseline_environment_summary. ...
    DensityChangeFromQuiet_pct = ...
    DensityChangeFromQuiet_pct;

baseline_environment_summary. ...
    CDChangeFromQuiet_pct = ...
    CDChangeFromQuiet_pct;

baseline_environment_summary. ...
    DragChangeFromQuiet_pct = ...
    DragChangeFromQuiet_pct;

baseline_environment_summary. ...
    CMyChangeFromQuiet_pct = ...
    CMyChangeFromQuiet_pct;

baseline_environment_summary. ...
    MyChangeFromQuiet_pct = ...
    MyChangeFromQuiet_pct;


%% Compact relative comparison

relative_environment_summary = ...
    baseline_environment_summary(:, { ...
    'Environment', ...
    'F107_Average', ...
    'F107_Daily', ...
    'Ap_Daily', ...
    'Density_kgm3', ...
    'DensityChangeFromQuiet_pct', ...
    'CD_ADBSat', ...
    'CDChangeFromQuiet_pct', ...
    'Drag_N', ...
    'DragChangeFromQuiet_pct', ...
    'CMy_B', ...
    'CMyChangeFromQuiet_pct', ...
    'My_Nm', ...
    'MyChangeFromQuiet_pct'});


fprintf('\n');
fprintf('====================================================\n');
fprintf('RELATIVE TO QUIET CASE AT %.0f km\n', ...
    cfg.orbit.altitude_km);
fprintf('====================================================\n\n');

disp(relative_environment_summary)


%% Summary

fprintf('\n');
fprintf('====================================================\n');
fprintf('ENVIRONMENTAL-SENSITIVITY SUMMARY\n');
fprintf('====================================================\n');


% Find quiet/reference/elevated rows at baseline altitude
for c = 1:nCases

    idx = find( ...
        idx_baseline & ...
        Environment == string(labels{c}), ...
        1);

    fprintf('\n%s case at %.0f km:\n', ...
        labels{c}, ...
        cfg.orbit.altitude_km);

    fprintf('Density:     %.8e kg/m^3\n', ...
        Density_kgm3(idx));

    fprintf('ADBSat CD:   %.9f\n', ...
        CD_ADBSat(idx));

    fprintf('Drag:        %.8e N\n', ...
        Drag_N(idx));

    fprintf('CMy:         %+.8e\n', ...
        CMy_B(idx));

    fprintf('My:          %+.8e N m\n', ...
        My_Nm(idx));

end


fprintf('\nMaximum baseline-altitude changes relative to quiet:\n');

fprintf('Density:     %.3f %%\n', ...
    max(abs(DensityChangeFromQuiet_pct)));

fprintf('ADBSat CD:   %.3f %%\n', ...
    max(abs(CDChangeFromQuiet_pct)));

fprintf('Drag:        %.3f %%\n', ...
    max(abs(DragChangeFromQuiet_pct)));

fprintf('CMy:         %.3f %%\n', ...
    max(abs(CMyChangeFromQuiet_pct)));

fprintf('My:          %.3f %%\n', ...
    max(abs(MyChangeFromQuiet_pct)));

fprintf(['\nThese values represent controlled environmental ' ...
    'sensitivity scenarios, not mission forecasts.\n']);


%% Plot

%% ================================================================
% DISSERTATION FIGURE 4.2
% Environmental sensitivity
% ================================================================

fig = figure( ...
    'Name','Environmental Sensitivity', ...
    'Color','w', ...
    'Position',[100 100 1500 620]);

t = tiledlayout(fig,1,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

% Different marker shapes make the environmental cases clear
% even when printed in greyscale.
markers = {'o','s','^'};

%% ================================================================
% PANEL (a) - DIMENSIONAL DRAG
% ================================================================

ax1 = nexttile(t,1);

hold(ax1,'on');
grid(ax1,'on');
box(ax1,'on');

hDrag = gobjects(nCases,1);

for c = 1:nCases

    idx = Environment == string(labels{c});

    % Sort by altitude before plotting
    x = Altitude_km(idx);
    y = Drag_N(idx);

    [x,order] = sort(x);
    y = y(order);

    hDrag(c) = semilogy( ...
        ax1, ...
        x, ...
        y, ...
        ['-' markers{c}], ...
        'LineWidth',1.8, ...
        'MarkerSize',9, ...
        'DisplayName',labels{c});

end

% Nominal design altitude
hNom1 = xline(ax1, ...
    cfg.orbit.altitude_km, ...
    '--k', ...
    'LineWidth',1.1);

hNom1.HandleVisibility = 'off';

xlabel(ax1,'Altitude [km]', ...
    'FontSize',16);

ylabel(ax1,'Drag [N]', ...
    'FontSize',16);

title(ax1,'(a) Dimensional drag', ...
    'FontSize',17, ...
    'FontWeight','bold');

legend(ax1, ...
    hDrag, ...
    labels, ...
    'Location','southwest', ...
    'FontSize',13);

xlim(ax1,[195 405]);
xticks(ax1,200:50:400);

set(ax1, ...
    'FontName','Times New Roman', ...
    'FontSize',14, ...
    'LineWidth',0.9, ...
    'Color','w', ...
    'XColor','k', ...
    'YColor','k', ...
    'GridColor',[0.72 0.72 0.72], ...
    'GridAlpha',0.40);

% Remove MATLAB toolbar from exported figure
ax1.Toolbar.Visible = 'off';


%% ================================================================
% PANEL (b) - NATIVE ADBSat DRAG COEFFICIENT
% ================================================================

ax2 = nexttile(t,2);

hold(ax2,'on');
grid(ax2,'on');
box(ax2,'on');

hCD = gobjects(nCases,1);

for c = 1:nCases

    idx = Environment == string(labels{c});

    x = Altitude_km(idx);
    y = CD_ADBSat(idx);

    [x,order] = sort(x);
    y = y(order);

    hCD(c) = plot( ...
        ax2, ...
        x, ...
        y, ...
        ['-' markers{c}], ...
        'LineWidth',1.8, ...
        'MarkerSize',9, ...
        'DisplayName',labels{c});

end

% Nominal design altitude
hNom2 = xline(ax2, ...
    cfg.orbit.altitude_km, ...
    '--k', ...
    'LineWidth',1.1);

hNom2.HandleVisibility = 'off';

xlabel(ax2,'Altitude [km]', ...
    'FontSize',16);

ylabel(ax2,'Native ADBSat C_D', ...
    'FontSize',16);

title(ax2,'(b) Drag coefficient', ...
    'FontSize',17, ...
    'FontWeight','bold');

legend(ax2, ...
    hCD, ...
    labels, ...
    'Location','best', ...
    'FontSize',13);

xlim(ax2,[195 405]);
xticks(ax2,200:50:400);

set(ax2, ...
    'FontName','Times New Roman', ...
    'FontSize',14, ...
    'LineWidth',0.9, ...
    'Color','w', ...
    'XColor','k', ...
    'YColor','k', ...
    'GridColor',[0.72 0.72 0.72], ...
    'GridAlpha',0.40);

ax2.Toolbar.Visible = 'off';


%% ================================================================
% SAVE RESULTS
% ================================================================

save( ...
    fullfile( ...
        cfg.paths.project_results_dir, ...
        'environment_sensitivity_summary.mat'), ...
    'environment_results', ...
    'baseline_environment_summary', ...
    'relative_environment_summary', ...
    'cfg');

writetable( ...
    environment_results, ...
    fullfile( ...
        cfg.paths.project_results_dir, ...
        'environment_sensitivity_results.csv'));

writetable( ...
    baseline_environment_summary, ...
    fullfile( ...
        cfg.paths.project_results_dir, ...
        'environment_sensitivity_baseline.csv'));

writetable( ...
    relative_environment_summary, ...
    fullfile( ...
        cfg.paths.project_results_dir, ...
        'environment_sensitivity_relative_to_quiet.csv'));


%% ================================================================
% SAVE DISSERTATION FIGURE
% ================================================================

png_file = fullfile( ...
    cfg.paths.project_results_dir, ...
    'Figure_4_2_environmental_sensitivity.png');

pdf_file = fullfile( ...
    cfg.paths.project_results_dir, ...
    'Figure_4_2_environmental_sensitivity.pdf');

exportgraphics( ...
    fig, ...
    png_file, ...
    'Resolution',600, ...
    'BackgroundColor','white');

exportgraphics( ...
    fig, ...
    pdf_file, ...
    'ContentType','vector', ...
    'BackgroundColor','white');


%% ================================================================
% COMPLETE
% ================================================================

fprintf('\n');
fprintf('Environmental sensitivity analysis complete.\n');

fprintf('Results saved in:\n%s\n', ...
    cfg.paths.project_results_dir);

fprintf('\nFigure 4.2 saved to:\n%s\n', ...
    png_file);