clear
clc
close all

%% ================================================================
% FIGURE 4.5 - CENTRE-OF-MASS AND LOCAL STABILITY SENSITIVITY
%
% Uses existing saved results only.
% No ADBSat cases are rerun.
%
% Panel (a):
%   Small-angle CMy results for the selected +6 mm CoM,
%   including the exact 0-deg reference and the fitted gradient
%   through the non-zero cases.
%
% Panel (b):
%   Operational CMy comparison for:
%       geometric origin
%       selected +6 mm X CoM
%       +34.5 mm local-neutral-gradient X CoM
%% ================================================================

%% Load configuration

if ~exist('cfg','var')
    project_config
end

model_name = cfg.model.name;

resultsDir = fullfile( ...
    cfg.paths.project_root, ...
    'results', ...
    model_name);

%% ================================================================
% LOAD EXISTING RESULTS
% ================================================================

comFile = fullfile( ...
    resultsDir, ...
    'com_xz_sensitivity_v03.mat');

smallFile = fullfile( ...
    resultsDir, ...
    'small_angle_pitch_summary.mat');

if ~isfile(comFile)
    error('CoM results file not found:\n%s',comFile);
end

if ~isfile(smallFile)
    error('Small-angle results file not found:\n%s',smallFile);
end

COM = load(comFile);
SMALL = load(smallFile);

%% ================================================================
% SMALL-ANGLE DATA
% ================================================================

smallTable = SMALL.results_small_angle;

aoa_small = smallTable.AoA_deg;
CMy_small = smallTable.CMy;

% Official derivative fit excludes exact zero
fitMask = aoa_small ~= 0;

alpha_fit_rad = deg2rad(aoa_small(fitMask));
CMy_fit = CMy_small(fitMask);

p = polyfit(alpha_fit_rad,CMy_fit,1);

alpha_line_deg = linspace(-2,2,300);
alpha_line_rad = deg2rad(alpha_line_deg);

CMy_line = polyval(p,alpha_line_rad);

% Separate exact-zero point for display
zeroMask = aoa_small == 0;

%% ================================================================
% OPERATIONAL CoM COMPARISON
% ================================================================

aoa_operational = COM.aoa_deg(:);

CMy_origin = COM.CMy_origin(:);
Cfz = COM.Cfz(:);
Cfx = COM.Cfx(:);
Lref = COM.Lref;

% Practical selected CoM
x_selected_m = 6.0e-3;
z_selected_m = 0;

% Official shadow-ON locally neutral-gradient CoM
x_neutral_m = 34.5e-3;
z_neutral_m = 0;

% Moment translation:
%
% CMy_new = CMy_origin
%         + (x/Lref)*Cfz
%         + (z/Lref)*Cfx

CMy_selected = ...
    CMy_origin ...
    + (x_selected_m/Lref).*Cfz ...
    + (z_selected_m/Lref).*Cfx;

CMy_neutral = ...
    CMy_origin ...
    + (x_neutral_m/Lref).*Cfz ...
    + (z_neutral_m/Lref).*Cfx;

%% ================================================================
% DISSERTATION FIGURE STYLE
% ================================================================

set(groot, ...
    'defaultFigureColor','w', ...
    'defaultFigureInvertHardcopy','off', ...
    'defaultAxesColor','w', ...
    'defaultAxesXColor','k', ...
    'defaultAxesYColor','k', ...
    'defaultAxesGridColor',[0.72 0.72 0.72], ...
    'defaultAxesGridAlpha',0.40, ...
    'defaultAxesFontName','Times New Roman', ...
    'defaultAxesFontSize',14, ...
    'defaultAxesLineWidth',0.9, ...
    'defaultAxesBox','on', ...
    'defaultTextColor','k', ...
    'defaultTextFontName','Times New Roman', ...
    'defaultLegendColor','w', ...
    'defaultLegendTextColor','k', ...
    'defaultLegendFontName','Times New Roman', ...
    'defaultLegendFontSize',12, ...
    'defaultLegendBox','off');

%% ================================================================
% CREATE FIGURE
% ================================================================

fig = figure( ...
    'Color','w', ...
    'Position',[100 100 1500 620]);

t = tiledlayout(fig,1,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

%% ================================================================
% PANEL (a) - SMALL-ANGLE BEHAVIOUR
% ================================================================

ax1 = nexttile(t,1);

hold(ax1,'on');
grid(ax1,'on');
box(ax1,'on');

% Non-zero calculated points used in fit
h1 = plot( ...
    ax1, ...
    aoa_small(fitMask), ...
    CMy_small(fitMask), ...
    'o', ...
    'LineStyle','none', ...
    'MarkerSize',9, ...
    'LineWidth',1.7);

% Exact zero reference
h2 = plot( ...
    ax1, ...
    aoa_small(zeroMask), ...
    CMy_small(zeroMask), ...
    'd', ...
    'LineStyle','none', ...
    'MarkerSize',10, ...
    'LineWidth',1.8);

% Linear fit excluding zero
h3 = plot( ...
    ax1, ...
    alpha_line_deg, ...
    CMy_line, ...
    '--', ...
    'LineWidth',1.7);

hZero1 = yline(ax1,0,'--', ...
    'LineWidth',0.9);

hZero1.HandleVisibility = 'off';

xlabel(ax1,'AoA [deg]', ...
    'FontSize',16);

ylabel(ax1,'C_{My}', ...
    'FontSize',16);

title(ax1,'(a) Small-angle pitch behaviour', ...
    'FontSize',17, ...
    'FontWeight','bold');

legend(ax1, ...
    [h1 h2 h3], ...
    { ...
    'Non-zero ADBSat cases', ...
    '0° reference', ...
    'Linear fit excluding 0°'}, ...
    'Location','best', ...
    'FontSize',12);

xlim(ax1,[-2.2 2.2]);
xticks(ax1,[-2 -1 0 1 2]);

set(ax1, ...
    'FontSize',14, ...
    'LineWidth',0.9);

ax1.Toolbar.Visible = 'off';

%% ================================================================
% PANEL (b) - OPERATIONAL CoM TRADE
% ================================================================

ax2 = nexttile(t,2);

hold(ax2,'on');
grid(ax2,'on');
box(ax2,'on');

h4 = plot( ...
    ax2, ...
    aoa_operational, ...
    CMy_origin, ...
    '-o', ...
    'LineWidth',1.7, ...
    'MarkerSize',8);

h5 = plot( ...
    ax2, ...
    aoa_operational, ...
    CMy_selected, ...
    '-s', ...
    'LineWidth',1.7, ...
    'MarkerSize',8);

h6 = plot( ...
    ax2, ...
    aoa_operational, ...
    CMy_neutral, ...
    '-^', ...
    'LineWidth',1.7, ...
    'MarkerSize',8);

hZero2 = yline(ax2,0,'--', ...
    'LineWidth',0.9);

hZero2.HandleVisibility = 'off';

xlabel(ax2,'AoA [deg]', ...
    'FontSize',16);

ylabel(ax2,'C_{My}', ...
    'FontSize',16);

title(ax2,'(b) Centre-of-mass sensitivity', ...
    'FontSize',17, ...
    'FontWeight','bold');

legend(ax2, ...
    [h4 h5 h6], ...
    { ...
    'Geometric origin', ...
    '+6 mm selected CoM', ...
    '+34.5 mm local-neutral CoM'}, ...
    'Location','best', ...
    'FontSize',12);

xlim(ax2,[-32 32]);
xticks(ax2,[-30 -20 -10 0 10 20 30]);

set(ax2, ...
    'FontSize',14, ...
    'LineWidth',0.9);

ax2.Toolbar.Visible = 'off';

%% ================================================================
% EXPORT
% ================================================================

pngFile = fullfile( ...
    resultsDir, ...
    'Figure_4_5_com_stability.png');

pdfFile = fullfile( ...
    resultsDir, ...
    'Figure_4_5_com_stability.pdf');

exportgraphics( ...
    fig, ...
    pngFile, ...
    'Resolution',600, ...
    'BackgroundColor','white');

exportgraphics( ...
    fig, ...
    pdfFile, ...
    'ContentType','vector', ...
    'BackgroundColor','white');

fprintf('\nFigure 4.5 created successfully.\n');
fprintf('PNG:\n%s\n\n',pngFile);
fprintf('PDF:\n%s\n',pdfFile);