clear
clc
close all

%% ================================================================
% FIGURE 4.3 - SENTMAN ACCOMMODATION SENSITIVITY
%
% Plot-only script using the final verified results.
% No ADBSat analysis is rerun.
%
% AoA = -30 deg : alpha = 0.4, 0.8, 1.0
% AoA =   0 deg : alpha = 0.4, 0.8, 0.9, 1.0
% AoA = +30 deg : alpha = 0.4, 0.8, 1.0
%
% At +/-30 deg, markers only are used because alpha = 0.9
% was not evaluated at those attitudes.
%% ================================================================


%% ---------------------------------------------------------------
% OUTPUT LOCATION
% ---------------------------------------------------------------

% Use project results folder if project_config is available.
% Otherwise save in the current working directory.

try
    project_config
    outputFolder = cfg.paths.project_results_dir;
catch
    outputFolder = pwd;
end

if ~exist(outputFolder,'dir')
    mkdir(outputFolder);
end


%% ---------------------------------------------------------------
% DISSERTATION FIGURE STYLE
% ---------------------------------------------------------------

set(groot, ...
    'defaultFigureColor','w', ...
    'defaultFigureInvertHardcopy','off', ...
    'defaultAxesColor','w', ...
    'defaultAxesXColor','k', ...
    'defaultAxesYColor','k', ...
    'defaultAxesZColor','k', ...
    'defaultAxesGridColor',[0.72 0.72 0.72], ...
    'defaultAxesMinorGridColor',[0.85 0.85 0.85], ...
    'defaultAxesGridAlpha',0.40, ...
    'defaultAxesMinorGridAlpha',0.20, ...
    'defaultAxesFontName','Times New Roman', ...
    'defaultAxesFontSize',14, ...
    'defaultAxesLineWidth',0.9, ...
    'defaultAxesBox','on', ...
    'defaultTextColor','k', ...
    'defaultTextFontName','Times New Roman', ...
    'defaultTextFontSize',14, ...
    'defaultLegendColor','w', ...
    'defaultLegendTextColor','k', ...
    'defaultLegendFontName','Times New Roman', ...
    'defaultLegendFontSize',13, ...
    'defaultLegendBox','off');


%% ================================================================
% FINAL VERIFIED DATA
% ================================================================

% ---------------- AoA = -30 deg ----------------

alpha_m30 = [0.4 0.8 1.0];

dragChange_m30 = [ ...
    21.85 ...
    11.49 ...
     0.00];

CMy_m30 = [ ...
   -1.5682e-2 ...
   -7.7460e-3 ...
    1.0550e-3];


% ---------------- AoA = 0 deg ----------------

alpha_0 = [0.4 0.8 0.9 1.0];

dragChange_0 = [ ...
    13.44 ...
     7.07 ...
     4.57 ...
     0.00];

CMy_0 = [ ...
    1.36636e-3 ...
    1.25785e-3 ...
    1.21530e-3 ...
    1.13752e-3];


% ---------------- AoA = +30 deg ----------------

alpha_p30 = [0.4 0.8 1.0];

dragChange_p30 = [ ...
    21.67 ...
    11.39 ...
     0.00];

CMy_p30 = [ ...
    1.6590e-2 ...
    8.5160e-3 ...
   -4.3700e-4];


%% ================================================================
% CREATE FIGURE
% ================================================================

fig = figure( ...
    'Color','w', ...
    'Units','pixels', ...
    'Position',[100 100 1500 620]);

t = tiledlayout(fig,1,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');


%% ================================================================
% PANEL (a) - DIMENSIONAL DRAG
% ================================================================

ax1 = nexttile(t,1);

hold(ax1,'on');
grid(ax1,'on');
box(ax1,'on');

% -30 deg: markers only
h1 = plot(ax1, ...
    alpha_m30, ...
    dragChange_m30, ...
    'o', ...
    'LineStyle','none', ...
    'MarkerSize',10, ...
    'LineWidth',1.8);

% 0 deg: line + markers because all four alpha cases exist
h2 = plot(ax1, ...
    alpha_0, ...
    dragChange_0, ...
    '-s', ...
    'MarkerSize',9, ...
    'LineWidth',1.8);

% +30 deg: markers only
h3 = plot(ax1, ...
    alpha_p30, ...
    dragChange_p30, ...
    '^', ...
    'LineStyle','none', ...
    'MarkerSize',10, ...
    'LineWidth',1.8);

% Zero reference line
hZero1 = yline(ax1,0,'--', ...
    'LineWidth',1.0);

hZero1.HandleVisibility = 'off';

xlabel(ax1,'Energy accommodation coefficient, \alpha', ...
    'FontSize',16);

ylabel(ax1,'Change in drag [%]', ...
    'FontSize',16);

title(ax1,'(a) Dimensional drag sensitivity', ...
    'FontSize',17, ...
    'FontWeight','bold');

legend(ax1, ...
    [h1 h2 h3], ...
    {'AoA = -30°','AoA = 0°','AoA = +30°'}, ...
    'Location','northeast', ...
    'FontSize',13);

xlim(ax1,[0.35 1.05]);
ylim(ax1,[-1 24]);

xticks(ax1,[0.4 0.6 0.8 0.9 1.0]);

set(ax1, ...
    'FontSize',14, ...
    'FontName','Times New Roman', ...
    'LineWidth',0.9);


%% ================================================================
% PANEL (b) - PITCHING-MOMENT COEFFICIENT
% ================================================================

ax2 = nexttile(t,2);

hold(ax2,'on');
grid(ax2,'on');
box(ax2,'on');

% -30 deg: markers only
h4 = plot(ax2, ...
    alpha_m30, ...
    CMy_m30, ...
    'o', ...
    'LineStyle','none', ...
    'MarkerSize',10, ...
    'LineWidth',1.8);

% 0 deg: line + markers
h5 = plot(ax2, ...
    alpha_0, ...
    CMy_0, ...
    '-s', ...
    'MarkerSize',9, ...
    'LineWidth',1.8);

% +30 deg: markers only
h6 = plot(ax2, ...
    alpha_p30, ...
    CMy_p30, ...
    '^', ...
    'LineStyle','none', ...
    'MarkerSize',10, ...
    'LineWidth',1.8);

% Zero reference line
hZero2 = yline(ax2,0,'--', ...
    'LineWidth',1.0);

hZero2.HandleVisibility = 'off';

xlabel(ax2,'Energy accommodation coefficient, \alpha', ...
    'FontSize',16);

ylabel(ax2,'C_{My}', ...
    'FontSize',16);

title(ax2,'(b) Pitching-moment coefficient', ...
    'FontSize',17, ...
    'FontWeight','bold');

legend(ax2, ...
    [h4 h5 h6], ...
    {'AoA = -30°','AoA = 0°','AoA = +30°'}, ...
    'Location','northeast', ...
    'FontSize',13);

xlim(ax2,[0.35 1.05]);
ylim(ax2,[-0.018 0.019]);

xticks(ax2,[0.4 0.6 0.8 0.9 1.0]);

set(ax2, ...
    'FontSize',14, ...
    'FontName','Times New Roman', ...
    'LineWidth',0.9);


%% ================================================================
% MAIN TITLE
% ================================================================

sgtitle(t, ...
    'Sentman Accommodation Sensitivity', ...
    'FontName','Times New Roman', ...
    'FontSize',19, ...
    'FontWeight','bold');


%% ================================================================
% EXPORT
% ================================================================

outputPNG = fullfile( ...
    outputFolder, ...
    'Figure_4_3_accommodation_sensitivity.png');

outputPDF = fullfile( ...
    outputFolder, ...
    'Figure_4_3_accommodation_sensitivity.pdf');

exportgraphics( ...
    fig, ...
    outputPNG, ...
    'Resolution',600, ...
    'BackgroundColor','white');

exportgraphics( ...
    fig, ...
    outputPDF, ...
    'ContentType','vector', ...
    'BackgroundColor','white');

fprintf('\nFigure 4.3 created successfully.\n');
fprintf('PNG saved to:\n%s\n\n',outputPNG);
fprintf('PDF saved to:\n%s\n',outputPDF);