%% high_agility_assessment.m
% High-agility aerodynamic assessment for disc_lenticular_v03.
%
% PURPOSE
% -------
% Characterise the aerodynamic loading of the final spacecraft over a
% much wider attitude envelope than the nominal +/-30 deg imaging range.
%
% This study assesses AERODYNAMIC COMPATIBILITY with high agility.
%
% It does NOT by itself prove spacecraft slew performance.
% True agility additionally depends on:
% - spacecraft moments of inertia;
% - actuator torque;
% - actuator momentum storage;
% - required slew angle;
% - required slew time;
% - settling / pointing requirements.
%
% Final aerodynamic configuration:
% - disc_lenticular_v03
% - fine 8800-panel mesh
% - 300 km
% - Sentman alpha = 1
% - shadow ON
% - solar OFF
% - selected design CoM = [+6, 0, 0] mm
%
% The high-agility study contains:
%
% 1. Pure pitch sweep to +/-90 deg
% 2. Pure sideslip sweep to +/-90 deg
% 3. Combined AoA/AoS cases up to +/-60 deg
%
% Raw ADBSat results are saved in a dedicated subfolder to avoid
% overwriting the established final operational results.

if ~exist('cfg','var')
    project_config
end

cfg_run = cfg;

cfg_run.flags.verbose = 0;
cfg_run.flags.shadow = 1;
cfg_run.flags.solar = 0;

%% ================================================================
% Dissertation figure style
% ================================================================

set(groot, ...
    'defaultFigureColor','w', ...
    'defaultFigureInvertHardcopy','off', ...
    'defaultAxesColor','w', ...
    'defaultAxesXColor','k', ...
    'defaultAxesYColor','k', ...
    'defaultAxesZColor','k', ...
    'defaultAxesGridColor',[0.70 0.70 0.70], ...
    'defaultAxesMinorGridColor',[0.82 0.82 0.82], ...
    'defaultAxesGridAlpha',0.35, ...
    'defaultAxesMinorGridAlpha',0.20, ...
    'defaultAxesFontName','Times New Roman', ...
    'defaultAxesFontSize',11, ...
    'defaultAxesLineWidth',0.8, ...
    'defaultAxesBox','on', ...
    'defaultTextColor','k', ...
    'defaultTextFontName','Times New Roman', ...
    'defaultTextFontSize',11, ...
    'defaultLineLineWidth',1.4, ...
    'defaultLineMarkerSize',6, ...
    'defaultLegendColor','w', ...
    'defaultLegendTextColor','k', ...
    'defaultLegendFontName','Times New Roman', ...
    'defaultLegendFontSize',10, ...
    'defaultLegendBox','off');

%% Configuration

model_name = cfg.model.name;

altitude_km = cfg.orbit.altitude_km;

gsi_model = 'sentman';

override = struct();
override.alpha = 1.0;

%% Confirm final design CoM

cfg_run.model.com_G_m = [ ...
    0.006;
    0;
    0];

%% Dedicated results directory

main_results_dir = ...
    cfg.paths.project_results_dir;

agility_raw_dir = fullfile( ...
    main_results_dir, ...
    'high_agility_raw');

if ~exist(agility_raw_dir,'dir')
    mkdir(agility_raw_dir);
end

cfg_run.paths.project_results_dir = ...
    agility_raw_dir;

%% Load final model reference quantities

model_file = fullfile( ...
    cfg.paths.model_dir, ...
    [model_name '.mat']);

if ~isfile(model_file)

    error( ...
        'Model file not found: %s', ...
        model_file);

end

S = load(model_file);

Lref_m = ...
    S.meshdata.Lref;

AreaRef_model_m2 = ...
    0.5 * sum(S.meshdata.Areas);

%% ================================================================
%  ATTITUDE MATRIX
%  ================================================================

% Wide pure-pitch characterisation.
%
% This extends the established operational +/-30 deg range to +/-90 deg.

pitch_angles = [ ...
    -90 ...
    -75 ...
    -60 ...
    -45 ...
    -30 ...
    -20 ...
    -10 ...
      0 ...
     10 ...
     20 ...
     30 ...
     45 ...
     60 ...
     75 ...
     90];

% Wide pure-sideslip characterisation.

sideslip_angles = pitch_angles;

% Combined attitudes.
%
% We do not use +/-90 deg in the combined grid because the axis sweeps
% already characterise those extreme orientations and it avoids placing
% unnecessary emphasis on angular-coordinate edge cases.

combined_angles = [ ...
    -60 ...
    -30 ...
      0 ...
     30 ...
     60];

%% Construct case matrix

case_matrix = [];

% Pure pitch

for i = 1:numel(pitch_angles)

    case_matrix(end+1,:) = [ ...
        pitch_angles(i), ...
        0];

end

% Pure sideslip

for i = 1:numel(sideslip_angles)

    case_matrix(end+1,:) = [ ...
        0, ...
        sideslip_angles(i)];

end

% Combined AoA/AoS attitudes

for i = 1:numel(combined_angles)

    for j = 1:numel(combined_angles)

        case_matrix(end+1,:) = [ ...
            combined_angles(i), ...
            combined_angles(j)];

    end

end

%% Remove duplicate attitude pairs

case_matrix = ...
    unique( ...
    case_matrix, ...
    'rows', ...
    'stable');

AoA_cases = ...
    case_matrix(:,1);

AoS_cases = ...
    case_matrix(:,2);

nCase = ...
    size(case_matrix,1);

%% ================================================================
%  PREALLOCATE
%  ================================================================

AoA_deg = ...
    AoA_cases;

AoS_deg = ...
    AoS_cases;

RunSuccessful = ...
    false(nCase,1);

DynamicPressure_Pa = ...
    NaN(nCase,1);

AreaProj_m2 = ...
    NaN(nCase,1);

AreaRef_m2 = ...
    NaN(nCase,1);

CD_ADBSat = ...
    NaN(nCase,1);

CD_projected = ...
    NaN(nCase,1);

Drag_N = ...
    NaN(nCase,1);

CFx_B = ...
    NaN(nCase,1);

CFy_B = ...
    NaN(nCase,1);

CFz_B = ...
    NaN(nCase,1);

CMx_B = ...
    NaN(nCase,1);

CMy_B = ...
    NaN(nCase,1);

CMz_B = ...
    NaN(nCase,1);

Mx_Nm = ...
    NaN(nCase,1);

My_Nm = ...
    NaN(nCase,1);

Mz_Nm = ...
    NaN(nCase,1);

MomentMagnitude_Nm = ...
    NaN(nCase,1);

ForceCoefficientMagnitude = ...
    NaN(nCase,1);

%% ================================================================
%  HEADER
%  ================================================================

fprintf('\n');
fprintf('====================================================\n');
fprintf('FINAL v03 HIGH-AGILITY AERODYNAMIC ASSESSMENT\n');
fprintf('====================================================\n');

fprintf('Model:       %s\n', ...
    model_name);

fprintf('Altitude:    %.1f km\n', ...
    altitude_km);

fprintf('GSIM:        Sentman alpha = 1\n');

fprintf('Shadow:      %d\n', ...
    cfg_run.flags.shadow);

fprintf('Solar:       %d\n', ...
    cfg_run.flags.solar);

fprintf( ...
    'Design CoM:  [%+.6f  %+.6f  %+.6f] m\n', ...
    cfg_run.model.com_G_m(1), ...
    cfg_run.model.com_G_m(2), ...
    cfg_run.model.com_G_m(3));

fprintf('Lref:        %.9f m\n', ...
    Lref_m);

fprintf('AreaRef:     %.9f m^2\n', ...
    AreaRef_model_m2);

fprintf('Total cases: %d\n\n', ...
    nCase);

fprintf('Study includes:\n');
fprintf('  pure pitch:    +/-90 deg\n');
fprintf('  pure sideslip: +/-90 deg\n');
fprintf('  combined grid: +/-60 deg\n\n');

%% ================================================================
%  RUN ADBSat
%  ================================================================

for k = 1:nCase

    aoa = ...
        AoA_cases(k);

    aos = ...
        AoS_cases(k);

    fprintf( ...
        'Case %2d of %2d: AoA = %+6.1f deg, AoS = %+6.1f deg\n', ...
        k, ...
        nCase, ...
        aoa, ...
        aos);

    try

        out = run_adbsat_case( ...
            cfg_run, ...
            model_name, ...
            altitude_km, ...
            aoa, ...
            aos, ...
            gsi_model, ...
            override);

        %% Dynamic pressure

        q = ...
            0.5 * ...
            out.rho_kgm3 * ...
            out.vinf_ms^2;

        DynamicPressure_Pa(k) = ...
            q;

        %% Geometry

        AreaProj_m2(k) = ...
            out.AreaProj_m2;

        AreaRef_m2(k) = ...
            out.AreaRef_m2;

        %% Drag

        CD_ADBSat(k) = ...
            -out.Cf_w(1);

        CD_projected(k) = ...
            CD_ADBSat(k) * ...
            AreaRef_m2(k) / ...
            AreaProj_m2(k);

        Drag_N(k) = ...
            q * ...
            AreaRef_m2(k) * ...
            CD_ADBSat(k);

        %% Body-axis force coefficients

        CFx_B(k) = ...
            out.Cf_B(1);

        CFy_B(k) = ...
            out.Cf_B(2);

        CFz_B(k) = ...
            out.Cf_B(3);

        ForceCoefficientMagnitude(k) = ...
            norm(out.Cf_B);

        %% Body-axis moment coefficients

        CMx_B(k) = ...
            out.Cm_B(1);

        CMy_B(k) = ...
            out.Cm_B(2);

        CMz_B(k) = ...
            out.Cm_B(3);

        %% Dimensional moments

        Mx_Nm(k) = ...
            q * ...
            AreaRef_m2(k) * ...
            Lref_m * ...
            CMx_B(k);

        My_Nm(k) = ...
            q * ...
            AreaRef_m2(k) * ...
            Lref_m * ...
            CMy_B(k);

        Mz_Nm(k) = ...
            q * ...
            AreaRef_m2(k) * ...
            Lref_m * ...
            CMz_B(k);

        MomentMagnitude_Nm(k) = ...
            sqrt( ...
            Mx_Nm(k)^2 + ...
            My_Nm(k)^2 + ...
            Mz_Nm(k)^2);

        RunSuccessful(k) = true;

    catch ME

        warning( ...
            'Case AoA=%+.1f, AoS=%+.1f failed:\n%s', ...
            aoa, ...
            aos, ...
            ME.message);

        RunSuccessful(k) = false;

    end

end

%% ================================================================
%  RESULTS TABLE
%  ================================================================

results_agility = table( ...
    AoA_deg, ...
    AoS_deg, ...
    RunSuccessful, ...
    DynamicPressure_Pa, ...
    AreaProj_m2, ...
    AreaRef_m2, ...
    CD_ADBSat, ...
    CD_projected, ...
    Drag_N, ...
    CFx_B, ...
    CFy_B, ...
    CFz_B, ...
    CMx_B, ...
    CMy_B, ...
    CMz_B, ...
    Mx_Nm, ...
    My_Nm, ...
    Mz_Nm, ...
    MomentMagnitude_Nm, ...
    ForceCoefficientMagnitude);

fprintf('\n');
fprintf('====================================================\n');
fprintf('HIGH-AGILITY AERODYNAMIC RESULTS\n');
fprintf('====================================================\n\n');

disp(results_agility);

%% ================================================================
%  REFERENCE CASE
%  ================================================================

idx_nominal = ...
    find( ...
    AoA_deg == 0 & ...
    AoS_deg == 0);

if numel(idx_nominal) ~= 1

    error( ...
        'Exactly one nominal 0/0 attitude is required.');

end

D_nominal = ...
    Drag_N(idx_nominal);

M_nominal = ...
    MomentMagnitude_Nm(idx_nominal);

%% Ratios

DragRatioToNominal = ...
    Drag_N / ...
    D_nominal;

%% ================================================================
%  IDENTIFY EXTREME CASES
%  ================================================================

valid = ...
    RunSuccessful;

[max_drag_N, local_idx] = ...
    max(Drag_N(valid));

valid_indices = ...
    find(valid);

idx_max_drag = ...
    valid_indices(local_idx);

[max_moment_Nm, local_idx] = ...
    max(MomentMagnitude_Nm(valid));

idx_max_moment = ...
    valid_indices(local_idx);

[max_abs_Mx, local_idx] = ...
    max(abs(Mx_Nm(valid)));

idx_max_Mx = ...
    valid_indices(local_idx);

[max_abs_My, local_idx] = ...
    max(abs(My_Nm(valid)));

idx_max_My = ...
    valid_indices(local_idx);

[max_abs_Mz, local_idx] = ...
    max(abs(Mz_Nm(valid)));

idx_max_Mz = ...
    valid_indices(local_idx);

%% ================================================================
%  PURE-PITCH AND PURE-SIDESLIP TABLES
%  ================================================================

pitch_mask = ...
    (AoS_deg == 0);

sideslip_mask = ...
    (AoA_deg == 0);

pitch_results = ...
    results_agility(pitch_mask,:);

sideslip_results = ...
    results_agility(sideslip_mask,:);

%% ================================================================
%  BAFFLE / IMAGING FLAG
%  ================================================================

% Existing geometric shielding result:
%
% approximately +/-31.43 deg pitch.
%
% This flag is applied ONLY to the pure-pitch cases.
% It identifies attitudes outside the currently demonstrated telescope
% baffle shielding range.
%
% It does NOT imply immediate failure; it means the present baffle
% geometry has not been demonstrated to shield the aperture there.

baffle_limit_deg = ...
    31.43;

PitchWithinBaffleLimit = ...
    abs(pitch_results.AoA_deg) <= ...
    baffle_limit_deg;

pitch_results.PitchWithinBaffleLimit = ...
    PitchWithinBaffleLimit;

%% ================================================================
%  AERODYNAMIC HIGH-AGILITY SUMMARY
%  ================================================================

fprintf('\n');
fprintf('====================================================\n');
fprintf('HIGH-AGILITY AERODYNAMIC SUMMARY\n');
fprintf('====================================================\n');

fprintf('\nNominal attitude:\n');

fprintf('Drag = %.8e N\n', ...
    D_nominal);

fprintf('Total aerodynamic moment magnitude = %.8e N m\n', ...
    M_nominal);

fprintf('\nMaximum drag in tested envelope:\n');

fprintf('Drag = %.8e N\n', ...
    max_drag_N);

fprintf('AoA = %+.1f deg\n', ...
    AoA_deg(idx_max_drag));

fprintf('AoS = %+.1f deg\n', ...
    AoS_deg(idx_max_drag));

fprintf('Drag / nominal = %.3f x\n', ...
    max_drag_N / D_nominal);

fprintf('\nMaximum total aerodynamic moment:\n');

fprintf('|M| = %.8e N m\n', ...
    max_moment_Nm);

fprintf('AoA = %+.1f deg\n', ...
    AoA_deg(idx_max_moment));

fprintf('AoS = %+.1f deg\n', ...
    AoS_deg(idx_max_moment));

fprintf('\nMaximum individual moment components:\n');

fprintf('|Mx|max = %.8e N m at AoA=%+.1f, AoS=%+.1f deg\n', ...
    max_abs_Mx, ...
    AoA_deg(idx_max_Mx), ...
    AoS_deg(idx_max_Mx));

fprintf('|My|max = %.8e N m at AoA=%+.1f, AoS=%+.1f deg\n', ...
    max_abs_My, ...
    AoA_deg(idx_max_My), ...
    AoS_deg(idx_max_My));

fprintf('|Mz|max = %.8e N m at AoA=%+.1f, AoS=%+.1f deg\n', ...
    max_abs_Mz, ...
    AoA_deg(idx_max_Mz), ...
    AoS_deg(idx_max_Mz));

fprintf('\nCurrent telescope-baffle pitch shielding limit:\n');

fprintf('+/- %.2f deg\n', ...
    baffle_limit_deg);

fprintf(['Pure-pitch attitudes outside this limit should be treated ' ...
    'as high-agility/off-nominal attitudes rather than validated ' ...
    'imaging attitudes with the current baffle.\n']);

%% ================================================================
%  OPTIONAL DYNAMIC-AGILITY ASSESSMENT
%  ================================================================

% ADBSat gives disturbance loads but NOT slew capability.
%
% To make a true high-agility pass/fail assessment, fill in actual or
% defensible spacecraft mass-property and actuator values below.
%
% Leave values as NaN until supported by the spacecraft design or
% literature/manufacturer data.

Ixx_kgm2 = NaN;
Iyy_kgm2 = NaN;
Izz_kgm2 = NaN;

Tx_available_Nm = NaN;
Ty_available_Nm = NaN;
Tz_available_Nm = NaN;

Hx_capacity_Nms = NaN;
Hy_capacity_Nms = NaN;
Hz_capacity_Nms = NaN;

% Representative manoeuvres for characterisation.
%
% These are NOT automatically requirements.
% Replace them if your supervisor specifies a particular slew requirement.

slew_angles_deg = [ ...
    30 ...
    45 ...
    60 ...
    90];

slew_times_s = [ ...
    10 ...
    20 ...
    30 ...
    60];

%% Kinematic requirements independent of inertia

nSlew = ...
    numel(slew_angles_deg) * ...
    numel(slew_times_s);

SlewAngle_deg = ...
    zeros(nSlew,1);

SlewTime_s = ...
    zeros(nSlew,1);

RequiredAngularAcceleration_rad_s2 = ...
    zeros(nSlew,1);

PeakAngularRate_deg_s = ...
    zeros(nSlew,1);

row = 0;

for i = 1:numel(slew_angles_deg)

    theta_rad = ...
        deg2rad( ...
        slew_angles_deg(i));

    for j = 1:numel(slew_times_s)

        row = row + 1;

        t = ...
            slew_times_s(j);

        % Symmetric bang-bang slew:
        %
        % accelerate for half the manoeuvre,
        % decelerate for half.
        %
        % theta = alpha*t^2/4
        %
        % therefore:
        %
        % alpha = 4*theta/t^2

        angular_accel = ...
            4 * theta_rad / ...
            t^2;

        omega_peak_rad_s = ...
            2 * theta_rad / ...
            t;

        SlewAngle_deg(row) = ...
            slew_angles_deg(i);

        SlewTime_s(row) = ...
            t;

        RequiredAngularAcceleration_rad_s2(row) = ...
            angular_accel;

        PeakAngularRate_deg_s(row) = ...
            rad2deg( ...
            omega_peak_rad_s);

    end

end

kinematic_agility = table( ...
    SlewAngle_deg, ...
    SlewTime_s, ...
    RequiredAngularAcceleration_rad_s2, ...
    PeakAngularRate_deg_s);

fprintf('\n');
fprintf('====================================================\n');
fprintf('KINEMATIC SLEW REQUIREMENTS\n');
fprintf('====================================================\n\n');

disp(kinematic_agility);

%% Dynamic assessment only when inertias are supplied

if all(isfinite([ ...
        Ixx_kgm2 ...
        Iyy_kgm2 ...
        Izz_kgm2]))

    I_axes = [ ...
        Ixx_kgm2 ...
        Iyy_kgm2 ...
        Izz_kgm2];

    aero_disturbance = [ ...
        max_abs_Mx ...
        max_abs_My ...
        max_abs_Mz];

    fprintf('\n');
    fprintf('====================================================\n');
    fprintf('DYNAMIC SLEW TORQUE REQUIREMENTS\n');
    fprintf('====================================================\n');

    for axis = 1:3

        if axis == 1
            axis_name = 'X';
        elseif axis == 2
            axis_name = 'Y';
        else
            axis_name = 'Z';
        end

        fprintf('\n%s axis:\n', ...
            axis_name);

        for r = 1:height(kinematic_agility)

            alpha_req = ...
                kinematic_agility. ...
                RequiredAngularAcceleration_rad_s2(r);

            torque_inertial = ...
                I_axes(axis) * ...
                alpha_req;

            % Conservative addition of the maximum aerodynamic
            % disturbance opposing the commanded slew.

            torque_total = ...
                torque_inertial + ...
                aero_disturbance(axis);

            fprintf( ...
                '%3.0f deg in %4.0f s: ' + ...
                'inertial %.4e Nm, ' + ...
                'with aero %.4e Nm\n', ...
                kinematic_agility.SlewAngle_deg(r), ...
                kinematic_agility.SlewTime_s(r), ...
                torque_inertial, ...
                torque_total);

        end

    end

else

    fprintf('\n');
    fprintf('====================================================\n');
    fprintf('DYNAMIC AGILITY STATUS\n');
    fprintf('====================================================\n');

    fprintf(['No spacecraft inertias have been entered, therefore ' ...
        'a genuine slew-torque pass/fail assessment has NOT yet ' ...
        'been made.\n']);

    fprintf(['The aerodynamic envelope above is valid, but true ' ...
        'high-agility capability requires Ixx/Iyy/Izz and supported ' ...
        'actuator torque/momentum values.\n']);

end

%% ================================================================
%  SAVE RESULTS
%  ================================================================

results_agility.DragRatioToNominal = ...
    DragRatioToNominal;

writetable( ...
    results_agility, ...
    fullfile( ...
        main_results_dir, ...
        'high_agility_aerodynamic_results.csv'));

writetable( ...
    pitch_results, ...
    fullfile( ...
        main_results_dir, ...
        'high_agility_pitch_results.csv'));

writetable( ...
    sideslip_results, ...
    fullfile( ...
        main_results_dir, ...
        'high_agility_sideslip_results.csv'));

writetable( ...
    kinematic_agility, ...
    fullfile( ...
        main_results_dir, ...
        'high_agility_kinematic_requirements.csv'));

save( ...
    fullfile( ...
        main_results_dir, ...
        'high_agility_assessment_summary.mat'), ...
    'results_agility', ...
    'pitch_results', ...
    'sideslip_results', ...
    'kinematic_agility', ...
    'cfg');

%% ================================================================
%  DISSERTATION FIGURE 4.6
%  ================================================================

fig = figure( ...
    'Name','Extended-Attitude Aerodynamic Assessment', ...
    'Color','w', ...
    'Position',[100 100 1500 620]);

t = tiledlayout(fig,1,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

%% ================================================================
%  PANEL (a) - EXTENDED PITCH DRAG
%  ================================================================

ax1 = nexttile(t,1);

hold(ax1,'on');
grid(ax1,'on');
box(ax1,'on');

plot( ...
    ax1, ...
    pitch_results.AoA_deg, ...
    pitch_results.Drag_N, ...
    '-o', ...
    'LineWidth',1.8, ...
    'MarkerSize',8);

% Operational pitch boundaries
xline(ax1,-30,'--k', ...
    'LineWidth',1.2, ...
    'HandleVisibility','off');

xline(ax1,+30,'--k', ...
    'LineWidth',1.2, ...
    'HandleVisibility','off');

xlabel(ax1,'AoA [deg]', ...
    'FontSize',16);

ylabel(ax1,'Drag [N]', ...
    'FontSize',16);

title(ax1,'(a) Extended-attitude drag', ...
    'FontSize',17, ...
    'FontWeight','bold');

xlim(ax1,[-95 95]);
xticks(ax1,-90:30:90);

set(ax1, ...
    'FontName','Times New Roman', ...
    'FontSize',14, ...
    'LineWidth',0.9, ...
    'Color','w', ...
    'XColor','k', ...
    'YColor','k', ...
    'GridColor',[0.72 0.72 0.72], ...
    'GridAlpha',0.40);

% Remove MATLAB axes toolbar
ax1.Toolbar.Visible = 'off';


%% ================================================================
%  PANEL (b) - TOTAL AERODYNAMIC MOMENT ENVELOPE
%  ================================================================

ax2 = nexttile(t,2);

hold(ax2,'on');
grid(ax2,'on');
box(ax2,'on');

scatter( ...
    ax2, ...
    AoA_deg(valid), ...
    AoS_deg(valid), ...
    85, ...
    MomentMagnitude_Nm(valid), ...
    'filled');

% Operational pitch boundaries
xline(ax2,-30,'--k', ...
    'LineWidth',1.2, ...
    'HandleVisibility','off');

xline(ax2,+30,'--k', ...
    'LineWidth',1.2, ...
    'HandleVisibility','off');

xlabel(ax2,'AoA [deg]', ...
    'FontSize',16);

ylabel(ax2,'AoS [deg]', ...
    'FontSize',16);

title(ax2,'(b) Total aerodynamic moment envelope', ...
    'FontSize',17, ...
    'FontWeight','bold');

xlim(ax2,[-95 95]);
ylim(ax2,[-95 95]);

xticks(ax2,-90:30:90);
yticks(ax2,-90:30:90);

set(ax2, ...
    'FontName','Times New Roman', ...
    'FontSize',14, ...
    'LineWidth',0.9, ...
    'Color','w', ...
    'XColor','k', ...
    'YColor','k', ...
    'GridColor',[0.72 0.72 0.72], ...
    'GridAlpha',0.40);

% Colour bar for total moment magnitude
cb = colorbar(ax2);
cb.Label.String = '|M| [N m]';
cb.Label.FontName = 'Times New Roman';
cb.Label.FontSize = 14;
cb.FontName = 'Times New Roman';
cb.FontSize = 12;

% Remove MATLAB axes toolbar
ax2.Toolbar.Visible = 'off';


%% ================================================================
%  DISSERTATION FIGURE 4.6
%  Extended-attitude pitch behaviour
%  ================================================================

fig = figure( ...
    'Name','Extended-Attitude Aerodynamic Assessment', ...
    'Color','w', ...
    'Position',[100 100 1500 620]);

t = tiledlayout(fig,1,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

%% ================================================================
%  PANEL (a) - DIMENSIONAL DRAG
%  ================================================================

ax1 = nexttile(t,1);

hold(ax1,'on');
grid(ax1,'on');
box(ax1,'on');

plot( ...
    ax1, ...
    pitch_results.AoA_deg, ...
    pitch_results.Drag_N, ...
    '-o', ...
    'LineWidth',1.8, ...
    'MarkerSize',8);

% Operational pitch boundaries
xline(ax1,-30,'--k', ...
    'LineWidth',1.2, ...
    'HandleVisibility','off');

xline(ax1,+30,'--k', ...
    'LineWidth',1.2, ...
    'HandleVisibility','off');

xlabel(ax1,'AoA [deg]', ...
    'FontSize',16);

ylabel(ax1,'Drag [N]', ...
    'FontSize',16);

title(ax1,'(a) Extended-attitude drag', ...
    'FontSize',17, ...
    'FontWeight','bold');

xlim(ax1,[-95 95]);
xticks(ax1,-90:30:90);

set(ax1, ...
    'FontName','Times New Roman', ...
    'FontSize',14, ...
    'LineWidth',0.9, ...
    'Color','w', ...
    'XColor','k', ...
    'YColor','k', ...
    'GridColor',[0.72 0.72 0.72], ...
    'GridAlpha',0.40);

ax1.Toolbar.Visible = 'off';

%% ================================================================
%  PANEL (b) - TOTAL AERODYNAMIC MOMENT MAGNITUDE
%  ================================================================

ax2 = nexttile(t,2);

hold(ax2,'on');
grid(ax2,'on');
box(ax2,'on');

plot( ...
    ax2, ...
    pitch_results.AoA_deg, ...
    pitch_results.MomentMagnitude_Nm, ...
    '-o', ...
    'LineWidth',1.8, ...
    'MarkerSize',8);

% Operational pitch boundaries
xline(ax2,-30,'--k', ...
    'LineWidth',1.2, ...
    'HandleVisibility','off');

xline(ax2,+30,'--k', ...
    'LineWidth',1.2, ...
    'HandleVisibility','off');

xlabel(ax2,'AoA [deg]', ...
    'FontSize',16);

ylabel(ax2,'|M| [N m]', ...
    'FontSize',16);

title(ax2,'(b) Total aerodynamic moment magnitude', ...
    'FontSize',17, ...
    'FontWeight','bold');

xlim(ax2,[-95 95]);
xticks(ax2,-90:30:90);

set(ax2, ...
    'FontName','Times New Roman', ...
    'FontSize',14, ...
    'LineWidth',0.9, ...
    'Color','w', ...
    'XColor','k', ...
    'YColor','k', ...
    'GridColor',[0.72 0.72 0.72], ...
    'GridAlpha',0.40);

ax2.Toolbar.Visible = 'off';

%% ================================================================
%  EXPORT
%  ================================================================

png_file = fullfile( ...
    main_results_dir, ...
    'Figure_4_6_extended_attitude.png');

pdf_file = fullfile( ...
    main_results_dir, ...
    'Figure_4_6_extended_attitude.pdf');

exportgraphics( ...
    fig, ...
    png_file, ...
    'Resolution',600, ...
    'BackgroundColor','white');

exportgraphics( ...
    fig, ...
    pdf_file, ...
    'ContentType','vector', ...
    'BackgroundColor','white');

fprintf('\nFigure 4.6 saved to:\n%s\n',png_file);