%% small_angle_shadow_diagnostic.m
%
% Shadow-OFF small-angle diagnostic for the final spacecraft geometry.
%
% PURPOSE
% -------
% This diagnostic assesses sensitivity of the local pitch response to the
% ADBSat shadowing treatment near the nominal grazing-incidence attitude.
%
% The official aerodynamic analysis uses shadow ON.
% This script intentionally repeats the small-angle calculation with
% shadow OFF as a modelling/numerical sensitivity diagnostic.
%
% The exact zero-degree case is retained for reference but excluded from
% all local-gradient fits because of the known grazing-incidence
% sensitivity.
%
% This version also records the body-axis Z-force coefficient so that the
% local-neutral X-CoM can be calculated using force and moment gradients
% obtained from the SAME shadow-OFF dataset.
%
% No interpolation between uncalculated aerodynamic cases is used.

if ~exist('cfg','var')
    project_config
end

cfg_run = cfg;

cfg_run.flags.verbose = 0;

% Diagnostic condition:
% shadowing deliberately disabled.
cfg_run.flags.shadow = 0;

% Solar pressure remains disabled for the aerodynamic analysis.
cfg_run.flags.solar = 0;

%% ================================================================
% SETTINGS
% ================================================================

model_name = cfg.model.name;

altitude_km = cfg.orbit.altitude_km;

aos_deg = 0;

% Small-angle pitch cases.
aoa_deg = [ ...
    -2
    -1
    -0.5
     0
     0.5
     1
     2];

gsi_model = cfg.gsi.baseline_model;

nCase = numel(aoa_deg);

%% ================================================================
% LOAD MODEL REFERENCE DATA
% ================================================================

model_file = fullfile( ...
    cfg.paths.model_dir, ...
    [model_name '.mat']);

if ~isfile(model_file)

    error( ...
        'ADBSat model file not found: %s', ...
        model_file);

end

S = load(model_file);

Lref_m = S.meshdata.Lref;

AreaRef_model_m2 = ...
    0.5 * sum(S.meshdata.Areas);

%% ================================================================
% PREALLOCATE
% ================================================================

AreaProj_m2 = zeros(nCase,1);

CD_ADBSat = zeros(nCase,1);

Drag_N = zeros(nCase,1);

% Body-axis Z-force coefficient.
CFz_B = zeros(nCase,1);

% Pitching-moment coefficient about selected design CoM.
CMy = zeros(nCase,1);

% Dimensional pitching moment.
My_Nm = zeros(nCase,1);

%% ================================================================
% HEADER
% ================================================================

fprintf('\n');
fprintf('====================================================\n');
fprintf('SHADOW-OFF SMALL-ANGLE DIAGNOSTIC\n');
fprintf('====================================================\n');

fprintf('Model:       %s\n', ...
    model_name);

fprintf('Altitude:    %.1f km\n', ...
    altitude_km);

fprintf('AoS:         %.1f deg\n', ...
    aos_deg);

fprintf('GSIM:        %s\n', ...
    gsi_model);

fprintf('Shadow:      %d\n', ...
    cfg_run.flags.shadow);

fprintf('Solar:       %d\n', ...
    cfg_run.flags.solar);

fprintf( ...
    'CoM [m]:     [%+.6f  %+.6f  %+.6f]\n', ...
    cfg_run.model.com_G_m(1), ...
    cfg_run.model.com_G_m(2), ...
    cfg_run.model.com_G_m(3));

fprintf('Lref:        %.9f m\n', ...
    Lref_m);

fprintf('AreaRef:     %.9f m^2\n', ...
    AreaRef_model_m2);

fprintf('\n');

fprintf(['NOTE: Shadowing is OFF in this diagnostic only. ' ...
    'The official analysis uses shadow ON.\n\n']);

%% ================================================================
% RUN SHADOW-OFF CASES
% ================================================================

for i = 1:nCase

    fprintf( ...
        'Case %d of %d: AoA = %+.1f deg\n', ...
        i, ...
        nCase, ...
        aoa_deg(i));

    out = run_adbsat_case( ...
        cfg_run, ...
        model_name, ...
        altitude_km, ...
        aoa_deg(i), ...
        aos_deg, ...
        gsi_model);

    %% Dynamic pressure

    q = ...
        0.5 * ...
        out.rho_kgm3 * ...
        out.vinf_ms^2;

    %% Geometry

    AreaProj_m2(i) = ...
        out.AreaProj_m2;

    %% Native ADBSat drag coefficient

    CD_ADBSat(i) = ...
        -out.Cf_w(1);

    %% Dimensional drag

    Drag_N(i) = ...
        q * ...
        out.AreaRef_m2 * ...
        CD_ADBSat(i);

    %% Body-axis force coefficient

    CFz_B(i) = ...
        out.Cf_B(3);

    %% Pitching moment coefficient

    CMy(i) = ...
        out.Cm_B(2);

    %% Dimensional pitching moment

    My_Nm(i) = ...
        q * ...
        out.AreaRef_m2 * ...
        Lref_m * ...
        CMy(i);

end

%% ================================================================
% LOCAL LINEAR FIT
% ================================================================
%
% Exact zero is deliberately excluded because of the known
% grazing-incidence/shadow-treatment sensitivity.
%
% Therefore the fit uses:
%
% -2, -1, -0.5, +0.5, +1, +2 deg

fitMask = ...
    aoa_deg ~= 0;

alpha_fit_rad = ...
    deg2rad(aoa_deg(fitMask));

%% ================================================================
% PITCH-MOMENT GRADIENT
% ================================================================

CMy_fit = ...
    CMy(fitMask);

p_My = polyfit( ...
    alpha_fit_rad, ...
    CMy_fit, ...
    1);

dCMy_dalpha = ...
    p_My(1);

CMy_intercept = ...
    p_My(2);

CMy_pred = ...
    polyval( ...
    p_My, ...
    alpha_fit_rad);

SSres_My = ...
    sum( ...
    (CMy_fit - CMy_pred).^2);

SStot_My = ...
    sum( ...
    (CMy_fit - mean(CMy_fit)).^2);

R2 = ...
    1 - ...
    SSres_My / ...
    SStot_My;

%% ================================================================
% Z-FORCE GRADIENT
% ================================================================

CFz_fit = ...
    CFz_B(fitMask);

p_Fz = polyfit( ...
    alpha_fit_rad, ...
    CFz_fit, ...
    1);

dCFz_dalpha = ...
    p_Fz(1);

CFz_intercept = ...
    p_Fz(2);

CFz_pred = ...
    polyval( ...
    p_Fz, ...
    alpha_fit_rad);

SSres_Fz = ...
    sum( ...
    (CFz_fit - CFz_pred).^2);

SStot_Fz = ...
    sum( ...
    (CFz_fit - mean(CFz_fit)).^2);

R2_CFz = ...
    1 - ...
    SSres_Fz / ...
    SStot_Fz;

%% ================================================================
% ONE-SIDED MOMENT-GRADIENT DIAGNOSTICS
% ================================================================
%
% Diagnostic only.
% These values help show any residual asymmetry across zero AoA.

negMask = ...
    aoa_deg < 0;

posMask = ...
    aoa_deg > 0;

p_neg = polyfit( ...
    deg2rad(aoa_deg(negMask)), ...
    CMy(negMask), ...
    1);

p_pos = polyfit( ...
    deg2rad(aoa_deg(posMask)), ...
    CMy(posMask), ...
    1);

dCMy_dalpha_neg = ...
    p_neg(1);

dCMy_dalpha_pos = ...
    p_pos(1);

%% ================================================================
% SHADOW-OFF LOCAL-NEUTRAL X-CoM
% ================================================================
%
% Moment translation for a change only in X-CoM:
%
% CMy_new =
% CMy_current +
% ((x_new - x_current)/Lref) * CFz
%
% Differentiating with respect to alpha:
%
% dCMy_new/dalpha =
% dCMy_current/dalpha +
% ((x_new - x_current)/Lref) * dCFz/dalpha
%
% Local neutral gradient:
%
% dCMy_new/dalpha = 0
%
% Therefore:
%
% x_neutral =
% x_current -
% Lref*(dCMy/dalpha)/(dCFz/dalpha)

x_current_m = ...
    cfg_run.model.com_G_m(1);

if abs(dCFz_dalpha) < 1e-12

    error( ...
        ['Shadow-OFF dCFz/dalpha is too small to determine ' ...
         'a neutral X-CoM reliably.']);

end

x_neutral_shadowOFF_m = ...
    x_current_m ...
    - ...
    Lref_m * ...
    dCMy_dalpha / ...
    dCFz_dalpha;

%% ================================================================
% RESULTS TABLE
% ================================================================

results_small_angle = table( ...
    aoa_deg, ...
    AreaProj_m2, ...
    CD_ADBSat, ...
    Drag_N, ...
    CFz_B, ...
    CMy, ...
    My_Nm, ...
    'VariableNames', { ...
    'AoA_deg', ...
    'AreaProj_m2', ...
    'CD_ADBSat', ...
    'Drag_N', ...
    'CFz_B', ...
    'CMy', ...
    'My_Nm'});

%% ================================================================
% DISPLAY RESULTS
% ================================================================

fprintf('\n');
fprintf('====================================================\n');
fprintf('LOCAL PITCH RESULTS\n');
fprintf('====================================================\n\n');

disp(results_small_angle);

%% ================================================================
% SUMMARY
% ================================================================

fprintf('\n');
fprintf('====================================================\n');
fprintf('SHADOW-OFF SMALL-ANGLE SUMMARY\n');
fprintf('====================================================\n');

fprintf('\nPitch-moment gradient:\n');

fprintf( ...
    'dCMy/dalpha = %+.10e per rad\n', ...
    dCMy_dalpha);

fprintf( ...
    'Fit intercept = %+.10e\n', ...
    CMy_intercept);

fprintf( ...
    'R^2 = %.10f\n', ...
    R2);

fprintf('\nZ-force gradient:\n');

fprintf( ...
    'dCFz/dalpha = %+.10e per rad\n', ...
    dCFz_dalpha);

fprintf( ...
    'Fit intercept = %+.10e\n', ...
    CFz_intercept);

fprintf( ...
    'R^2 = %.10f\n', ...
    R2_CFz);

fprintf('\nOne-sided moment-gradient diagnostics:\n');

fprintf( ...
    'Negative AoA side: %+.10e per rad\n', ...
    dCMy_dalpha_neg);

fprintf( ...
    'Positive AoA side: %+.10e per rad\n', ...
    dCMy_dalpha_pos);

%% Exact zero reference

idx0 = ...
    find(aoa_deg == 0,1);

fprintf('\nExact zero-degree reference:\n');

fprintf( ...
    'CFz(0 deg) = %+.10e\n', ...
    CFz_B(idx0));

fprintf( ...
    'CMy(0 deg) = %+.10e\n', ...
    CMy(idx0));

fprintf( ...
    'My(0 deg)  = %+.10e N m\n', ...
    My_Nm(idx0));

%% Neutral CoM result

fprintf('\n');
fprintf('====================================================\n');
fprintf('SHADOW-OFF LOCAL-NEUTRAL X-CoM\n');
fprintf('====================================================\n');

fprintf( ...
    'Current X-CoM        = %+.6f mm\n', ...
    1000*x_current_m);

fprintf( ...
    'dCMy/dalpha          = %+.10e rad^-1\n', ...
    dCMy_dalpha);

fprintf( ...
    'dCFz/dalpha          = %+.10e rad^-1\n', ...
    dCFz_dalpha);

fprintf( ...
    'Neutral X-CoM        = %+.6f mm\n', ...
    1000*x_neutral_shadowOFF_m);

fprintf('====================================================\n');

fprintf(['\nThis neutral position is a shadow-OFF numerical/' ...
    'modelling diagnostic and is not the selected spacecraft CoM.\n']);

%% ================================================================
% OUTPUT FILES
% ================================================================

results_dir = ...
    cfg.paths.project_results_dir;

if ~exist(results_dir,'dir')
    mkdir(results_dir);
end

csv_file = fullfile( ...
    results_dir, ...
    'small_angle_shadowOFF_diagnostic.csv');

mat_file = fullfile( ...
    results_dir, ...
    'small_angle_shadowOFF_diagnostic.mat');

png_file = fullfile( ...
    results_dir, ...
    'small_angle_shadowOFF_diagnostic.png');

%% ================================================================
% SAVE CSV
% ================================================================

writetable( ...
    results_small_angle, ...
    csv_file);

%% ================================================================
% SAVE MAT FILE
% ================================================================

save( ...
    mat_file, ...
    'results_small_angle', ...
    'dCMy_dalpha', ...
    'CMy_intercept', ...
    'R2', ...
    'dCMy_dalpha_neg', ...
    'dCMy_dalpha_pos', ...
    'dCFz_dalpha', ...
    'CFz_intercept', ...
    'R2_CFz', ...
    'x_current_m', ...
    'x_neutral_shadowOFF_m', ...
    'Lref_m', ...
    'cfg');

%% ================================================================
% DIAGNOSTIC FIGURE
% ================================================================

fig = figure( ...
    'Name','Shadow-OFF Small-Angle Diagnostic', ...
    'Color','w', ...
    'Position',[100 100 1400 600]);

t = tiledlayout( ...
    fig, ...
    1, ...
    2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

%% Panel (a): CMy

ax1 = nexttile(t,1);

hold(ax1,'on');
grid(ax1,'on');
box(ax1,'on');

% Non-zero calculated cases
plot( ...
    ax1, ...
    aoa_deg(fitMask), ...
    CMy(fitMask), ...
    'o', ...
    'MarkerSize',8, ...
    'LineWidth',1.4, ...
    'DisplayName','Non-zero ADBSat cases');

% Exact zero shown separately
plot( ...
    ax1, ...
    aoa_deg(idx0), ...
    CMy(idx0), ...
    'd', ...
    'MarkerSize',9, ...
    'LineWidth',1.4, ...
    'DisplayName','Exact zero');

% Linear fit through non-zero cases
alpha_plot_deg = ...
    linspace( ...
    min(aoa_deg(fitMask)), ...
    max(aoa_deg(fitMask)), ...
    200);

CMy_plot = ...
    polyval( ...
    p_My, ...
    deg2rad(alpha_plot_deg));

plot( ...
    ax1, ...
    alpha_plot_deg, ...
    CMy_plot, ...
    '-', ...
    'LineWidth',1.6, ...
    'DisplayName','Non-zero linear fit');

xlabel( ...
    ax1, ...
    'AoA [deg]');

ylabel( ...
    ax1, ...
    'C_{My}');

title( ...
    ax1, ...
    '(a) Pitching-moment coefficient');

legend( ...
    ax1, ...
    'Location','best');

set( ...
    ax1, ...
    'FontName','Times New Roman', ...
    'FontSize',13, ...
    'LineWidth',0.9);

ax1.Toolbar.Visible = 'off';

%% Panel (b): CFz

ax2 = nexttile(t,2);

hold(ax2,'on');
grid(ax2,'on');
box(ax2,'on');

plot( ...
    ax2, ...
    aoa_deg(fitMask), ...
    CFz_B(fitMask), ...
    'o', ...
    'MarkerSize',8, ...
    'LineWidth',1.4, ...
    'DisplayName','Non-zero ADBSat cases');

plot( ...
    ax2, ...
    aoa_deg(idx0), ...
    CFz_B(idx0), ...
    'd', ...
    'MarkerSize',9, ...
    'LineWidth',1.4, ...
    'DisplayName','Exact zero');

CFz_plot = ...
    polyval( ...
    p_Fz, ...
    deg2rad(alpha_plot_deg));

plot( ...
    ax2, ...
    alpha_plot_deg, ...
    CFz_plot, ...
    '-', ...
    'LineWidth',1.6, ...
    'DisplayName','Non-zero linear fit');

xlabel( ...
    ax2, ...
    'AoA [deg]');

ylabel( ...
    ax2, ...
    'C_{Fz}');

title( ...
    ax2, ...
    '(b) Body-axis Z-force coefficient');

legend( ...
    ax2, ...
    'Location','best');

set( ...
    ax2, ...
    'FontName','Times New Roman', ...
    'FontSize',13, ...
    'LineWidth',0.9);

ax2.Toolbar.Visible = 'off';

%% Save diagnostic figure

exportgraphics( ...
    fig, ...
    png_file, ...
    'Resolution',600, ...
    'BackgroundColor','white');

%% ================================================================
% COMPLETE
% ================================================================

fprintf('\n');
fprintf('Shadow-OFF diagnostic complete.\n');

fprintf('\nCSV saved to:\n%s\n', ...
    csv_file);

fprintf('\nMAT file saved to:\n%s\n', ...
    mat_file);

fprintf('\nDiagnostic figure saved to:\n%s\n', ...
    png_file);