%% stability_com_trade_shadowON_v03.m
% Final shadow-ON local pitch derivative and CoM trade study.
%
% This reruns ONLY the six required non-zero small-angle cases:
%
% AoA = -2, -1, -0.5, +0.5, +1, +2 deg
%
% Conditions:
% - disc_lenticular_v03
% - 300 km
% - AoS = 0 deg
% - Sentman alpha = 1
% - Shadow ON
% - Solar OFF
% - selected design CoM = [+6, 0, 0] mm
%
% A dedicated result folder is used so these shadow-ON raw files
% cannot be overwritten by the earlier shadow-OFF diagnostic.

if ~exist('cfg','var')
    project_config
end


%% Case configuration

cfg_case = cfg;

cfg_case.flags.verbose = 0;
cfg_case.flags.shadow = 1;
cfg_case.flags.solar = 0;

model_name = 'disc_lenticular_v03';

altitude_km = 300;

aos_deg = 0;

aoa_deg = [ ...
    -2 ...
    -1 ...
    -0.5 ...
     0.5 ...
     1 ...
     2];


%% Explicit baseline GSI condition

gsi_model = 'sentman';

override = struct();

override.alpha = 1.0;


%% Selected practical design CoM

cfg_case.model.com_G_m = [ ...
    0.006;
    0;
    0];


%% Dedicated shadow-ON raw-results folder

main_results_dir = ...
    cfg.paths.project_results_dir;

shadow_results_dir = fullfile( ...
    main_results_dir, ...
    'stability_shadowON_raw');

if ~exist(shadow_results_dir,'dir')
    mkdir(shadow_results_dir);
end

cfg_case.paths.project_results_dir = ...
    shadow_results_dir;


%% Load final model

model_file = fullfile( ...
    cfg.paths.model_dir, ...
    [model_name '.mat']);

if ~isfile(model_file)

    error( ...
        'Model file not found: %s', ...
        model_file);

end

S = load(model_file);


%% Reference quantities

Lref_m = ...
    S.meshdata.Lref;

% ADBSat reference area = half total surface area
AreaRef_m2 = ...
    0.5 * sum(S.meshdata.Areas);


%% Preallocate

nCase = ...
    numel(aoa_deg);

Cfx_B = ...
    zeros(nCase,1);

Cfz_B = ...
    zeros(nCase,1);

CMy_origin = ...
    zeros(nCase,1);

CMy_design = ...
    zeros(nCase,1);

rho_kgm3 = ...
    zeros(nCase,1);

vinf_ms = ...
    zeros(nCase,1);


%% Header

fprintf('\n');
fprintf('====================================================\n');
fprintf('FINAL v03 SHADOW-ON LOCAL STABILITY / CoM TRADE\n');
fprintf('====================================================\n');

fprintf('Model:      %s\n', ...
    model_name);

fprintf('Altitude:   %.1f km\n', ...
    altitude_km);

fprintf('AoS:        %.1f deg\n', ...
    aos_deg);

fprintf('AoA fit:    -2, -1, -0.5, +0.5, +1, +2 deg\n');

fprintf('GSIM:       Sentman alpha = 1\n');

fprintf('Shadow:     %d\n', ...
    cfg_case.flags.shadow);

fprintf('Solar:      %d\n', ...
    cfg_case.flags.solar);

fprintf( ...
    'Design CoM: [%+.6f  %+.6f  %+.6f] m\n', ...
    cfg_case.model.com_G_m(1), ...
    cfg_case.model.com_G_m(2), ...
    cfg_case.model.com_G_m(3));

fprintf('Lref:       %.9f m\n', ...
    Lref_m);

fprintf('AreaRef:    %.9f m^2\n\n', ...
    AreaRef_m2);


%% Run six official shadow-ON cases

for i = 1:nCase

    fprintf( ...
        'Case %d of %d: AoA = %+.1f deg\n', ...
        i, ...
        nCase, ...
        aoa_deg(i));


    out = run_adbsat_case( ...
        cfg_case, ...
        model_name, ...
        altitude_km, ...
        aoa_deg(i), ...
        aos_deg, ...
        gsi_model, ...
        override);


    %% Body-axis force coefficients

    Cfx_B(i) = ...
        out.Cf_B(1);

    Cfz_B(i) = ...
        out.Cf_B(3);


    %% Pitch moment about geometric origin

    CMy_origin(i) = ...
        out.Cm_origin_B(2);


    %% Pitch moment about +6 mm design CoM

    CMy_design(i) = ...
        out.Cm_B(2);


    %% Environment

    rho_kgm3(i) = ...
        out.rho_kgm3;

    vinf_ms(i) = ...
        out.vinf_ms;

end


%% Convert AoA to radians

alpha_rad = ...
    deg2rad(aoa_deg(:));


%% Fit local normal-force derivative

p_fz = ...
    polyfit( ...
    alpha_rad, ...
    Cfz_B, ...
    1);

dCfz_dalpha = ...
    p_fz(1);


%% Fit local pitch derivative about geometric origin

p_origin = ...
    polyfit( ...
    alpha_rad, ...
    CMy_origin, ...
    1);

dCMy_origin_dalpha = ...
    p_origin(1);


%% Fit local pitch derivative about +6 mm design CoM

p_design = ...
    polyfit( ...
    alpha_rad, ...
    CMy_design, ...
    1);

dCMy_design_dalpha = ...
    p_design(1);


%% Calculate fitted values

pred_fz = ...
    polyval( ...
    p_fz, ...
    alpha_rad);

pred_origin = ...
    polyval( ...
    p_origin, ...
    alpha_rad);

pred_design = ...
    polyval( ...
    p_design, ...
    alpha_rad);


%% R-squared: normal force

SSres_fz = ...
    sum( ...
    (Cfz_B - pred_fz).^2);

SStot_fz = ...
    sum( ...
    (Cfz_B - mean(Cfz_B)).^2);

R2_fz = ...
    1 - SSres_fz/SStot_fz;


%% R-squared: origin pitching moment

SSres_origin = ...
    sum( ...
    (CMy_origin - pred_origin).^2);

SStot_origin = ...
    sum( ...
    (CMy_origin - mean(CMy_origin)).^2);

R2_origin = ...
    1 - SSres_origin/SStot_origin;


%% R-squared: +6 mm pitching moment

SSres_design = ...
    sum( ...
    (CMy_design - pred_design).^2);

SStot_design = ...
    sum( ...
    (CMy_design - mean(CMy_design)).^2);

R2_design = ...
    1 - SSres_design/SStot_design;


%% Calculate local-neutral X CoM
%
% For z_G = 0:
%
% CMy_new =
% CMy_origin + (x_G/Lref)*Cfz
%
% Therefore:
%
% dCMy_new/dalpha =
% dCMy_origin/dalpha
% + (x_G/Lref)*dCfz/dalpha
%
% Set derivative equal to zero and solve for x_G.

if abs(dCfz_dalpha) < 1e-12

    error( ...
        'dCfz/dalpha is too small to determine a neutral X CoM.');

end


x_neutral_m = ...
    -dCMy_origin_dalpha * ...
    Lref_m / ...
    dCfz_dalpha;


%% Independent cross-check from +6 mm derivative

x_design_m = ...
    cfg_case.model.com_G_m(1);

x_neutral_crosscheck_m = ...
    x_design_m ...
    - dCMy_design_dalpha * ...
    Lref_m / ...
    dCfz_dalpha;


%% Calculate moment curve at local-neutral X CoM

CMy_neutral = ...
    CMy_origin ...
    + (x_neutral_m/Lref_m) .* ...
    Cfz_B;


%% Verify derivative at neutral CoM

p_neutral = ...
    polyfit( ...
    alpha_rad, ...
    CMy_neutral, ...
    1);

dCMy_neutral_dalpha = ...
    p_neutral(1);


%% Dimensional local derivative at 300 km

q_300_Pa = ...
    0.5 * ...
    rho_kgm3(1) * ...
    vinf_ms(1)^2;

dMy_design_dalpha_300 = ...
    q_300_Pa * ...
    AreaRef_m2 * ...
    Lref_m * ...
    dCMy_design_dalpha;


%% Dynamic-pressure-scaled 200 km estimate
%
% This does NOT represent a separately fitted derivative at 200 km.
% It scales the 300 km coefficient derivative by 200 km dynamic pressure.

[param_eq_200, ~] = ...
    build_freestream( ...
    cfg, ...
    200);

q_200_Pa = ...
    0.5 * ...
    param_eq_200.rho(6) * ...
    param_eq_200.vinf^2;

dMy_design_dalpha_200_scaled = ...
    q_200_Pa * ...
    AreaRef_m2 * ...
    Lref_m * ...
    dCMy_design_dalpha;


%% Results table

results_stability_shadowON = table( ...
    aoa_deg(:), ...
    Cfx_B, ...
    Cfz_B, ...
    CMy_origin, ...
    CMy_design, ...
    CMy_neutral, ...
    'VariableNames', { ...
    'AoA_deg', ...
    'Cfx_B', ...
    'Cfz_B', ...
    'CMy_origin', ...
    'CMy_designPlus6mm', ...
    'CMy_localNeutral'});


fprintf('\n');
fprintf('====================================================\n');
fprintf('SHADOW-ON LOCAL DATA\n');
fprintf('====================================================\n\n');

disp(results_stability_shadowON);


%% Derivative results

fprintf('\n');
fprintf('====================================================\n');
fprintf('SHADOW-ON LOCAL DERIVATIVE RESULTS\n');
fprintf('====================================================\n');

fprintf( ...
    'dCfz/dalpha at origin:       %+.8e per rad\n', ...
    dCfz_dalpha);

fprintf( ...
    'R^2 Cfz fit:                 %.8f\n\n', ...
    R2_fz);


fprintf( ...
    'dCMy/dalpha at origin:       %+.8e per rad\n', ...
    dCMy_origin_dalpha);

fprintf( ...
    'R^2 origin CMy fit:          %.8f\n\n', ...
    R2_origin);


fprintf( ...
    'dCMy/dalpha at +6 mm CoM:    %+.8e per rad\n', ...
    dCMy_design_dalpha);

fprintf( ...
    'R^2 +6 mm CMy fit:           %.8f\n\n', ...
    R2_design);


fprintf( ...
    'dCMy/dalpha at neutral CoM:  %+.8e per rad\n', ...
    dCMy_neutral_dalpha);


%% CoM trade

fprintf('\n');
fprintf('====================================================\n');
fprintf('FINAL SHADOW-ON CENTRE-OF-MASS TRADE\n');
fprintf('====================================================\n');

fprintf( ...
    'Selected practical design X CoM:   +6.000 mm\n');

fprintf( ...
    'Exact +/-30 deg LS optimum X:      +5.898 mm\n');

fprintf( ...
    'Exact +/-30 deg LS optimum Z:      +0.392 mm\n');


fprintf('\n');

fprintf( ...
    'Local-neutral X CoM:               %+.3f mm\n', ...
    x_neutral_m * 1000);

fprintf( ...
    'Cross-check local-neutral X CoM:   %+.3f mm\n', ...
    x_neutral_crosscheck_m * 1000);

fprintf( ...
    'Additional shift from +6 mm:       %+.3f mm\n', ...
    (x_neutral_m - x_design_m) * 1000);


fprintf('\n');

fprintf( ...
    ['Interpretation: the CoM that minimises RMS pitching moment ' ...
    'over the +/-30 deg operational envelope is not necessarily ' ...
    'the same location that gives a zero local pitch derivative.\n']);


%% Dimensional derivative

fprintf('\n');
fprintf('====================================================\n');
fprintf('DIMENSIONAL LOCAL PITCH DERIVATIVE\n');
fprintf('====================================================\n');

fprintf('At 300 km:\n');

fprintf( ...
    'dMy/dalpha = %+.8e N m/rad\n', ...
    dMy_design_dalpha_300);


fprintf('\n');

fprintf('200 km dynamic-pressure-scaled estimate:\n');

fprintf( ...
    'dMy/dalpha = %+.8e N m/rad\n', ...
    dMy_design_dalpha_200_scaled);


fprintf('\n');

fprintf( ...
    ['The 200 km value is an analytical dynamic-pressure scaling ' ...
    'of the 300 km coefficient derivative, not a separately fitted ' ...
    '200 km aerodynamic derivative.\n']);


%% Save summary structure

summary = struct();

summary.Lref_m = ...
    Lref_m;

summary.AreaRef_m2 = ...
    AreaRef_m2;

summary.dCfz_dalpha = ...
    dCfz_dalpha;

summary.dCMy_origin_dalpha = ...
    dCMy_origin_dalpha;

summary.dCMy_design_dalpha = ...
    dCMy_design_dalpha;

summary.dCMy_neutral_dalpha = ...
    dCMy_neutral_dalpha;

summary.R2_fz = ...
    R2_fz;

summary.R2_origin = ...
    R2_origin;

summary.R2_design = ...
    R2_design;

summary.x_design_m = ...
    x_design_m;

summary.x_neutral_m = ...
    x_neutral_m;

summary.x_neutral_crosscheck_m = ...
    x_neutral_crosscheck_m;

summary.dMy_design_dalpha_300 = ...
    dMy_design_dalpha_300;

summary.dMy_design_dalpha_200_scaled = ...
    dMy_design_dalpha_200_scaled;


%% Save CSV

writetable( ...
    results_stability_shadowON, ...
    fullfile( ...
        main_results_dir, ...
        'stability_com_trade_shadowON_data.csv'));


%% Save MAT

save( ...
    fullfile( ...
        main_results_dir, ...
        'stability_com_trade_shadowON_summary.mat'), ...
    'results_stability_shadowON', ...
    'summary', ...
    'cfg');


%% Plot

figure( ...
    'Name', ...
    'Final v03 Shadow-ON Local CoM Trade');


plot( ...
    aoa_deg, ...
    CMy_origin, ...
    '-o', ...
    'LineWidth',1.5, ...
    'DisplayName','Geometric origin');

hold on;
grid on;


plot( ...
    aoa_deg, ...
    CMy_design, ...
    '-o', ...
    'LineWidth',1.5, ...
    'DisplayName','Selected +6 mm X CoM');


plot( ...
    aoa_deg, ...
    CMy_neutral, ...
    '-o', ...
    'LineWidth',1.5, ...
    'DisplayName','Local-neutral X CoM');


yline(0,'--');


xlabel('AoA [deg]');

ylabel('C_{My}');

title( ...
    'disc\_lenticular\_v03 Shadow-ON Local CoM Trade');


legend( ...
    'Location', ...
    'best');


%% Export figure

exportgraphics( ...
    gcf, ...
    fullfile( ...
        main_results_dir, ...
        'stability_com_trade_shadowON.png'), ...
    'Resolution',300);


%% Finish

fprintf('\n');

fprintf( ...
    'Corrected shadow-ON stability/CoM analysis complete.\n');

fprintf( ...
    'Dedicated shadow-ON raw files saved in:\n%s\n', ...
    shadow_results_dir);

fprintf( ...
    'Summary results saved in:\n%s\n', ...
    main_results_dir);